eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 5000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
spring:
  application:
    name: gateway-server
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411
zuul:
  routes:
    user_shiro-server:
      path: /api/user/**
      serviceId: user_shiro-server
      sensitiveHeaders:
    HRS-server:
      path: /api/HRS/**
      serviceId: HRS-server
      sensitiveHeaders:
    FMS-EMS-server:
      path: /api/FMS-EMS/**
      serviceId: FMS-EMS-server
      sensitiveHeaders:
    MIMS-server:
      path: /api/MIMS/**
      serviceId: MIMS-server
      sensitiveHeaders:
    MMS-server:
      path: /api/MMS/**
      serviceId: MMS-server
      sensitiveHeaders:

  host:
    connect-timeout-millis: 200000
    socket-timeout-millis: 200000